location: .gitman
sources:
- name: hls_lfcd_lds_driver
  repo: https://github.com/ROBOTIS-GIT/hls_lfcd_lds_driver.git
  rev: 4684a80cbac85b94bd7578898c78b9e697c1be9f
  link: src/hls_lfcd_lds_driver
  #  scripts:
  #- git submodule update --init --recursive


- name: openslam_gmapping
  repo: https://github.com/ros-perception/openslam_gmapping
  rev: c716f0192131029b31a49554f8c11353d29819a5
  link: src/openslam_gmapping

- name: slam_gmapping
  repo: https://github.com/ros-perception/slam_gmapping
  rev: 5a707e079364ab9f5349c72310f31bfed4a6c834
  link: src/slam_gmapping

- name: turtlebot3
  repo: git@github.com:ovgu-FINken/turtlebot3.git
  rev: master
  link: src/turtlebot3

- name: turtlebot3_msgs
  repo: https://github.com/ROBOTIS-GIT/turtlebot3_msgs.git
  rev: 036a68972d967c813dad84a4dfcee52f425e7f40
  link: src/turtlebot3_msgs

- name: turtlebot3_simulations
  repo: https://github.com/ROBOTIS-GIT/turtlebot3_simulations.git
  rev: master
  link: src/turtlebot3_simulations

- name: uncertainty_grid
  repo: git@github.com:ovgu-FINken/tracking_uncertainty_grid.git
  rev: master
  link: src/tracking_uncertainty_grid

- name: ranging
  repo: git@github.com:ovgu-FINken/driving_swarm_positioning
  rev: basti
  link: src/driving_swarm_positioning

- name: pheromones
  repo: git@github.com:ovgu-FINken/driving_swarm_pheromones.git
  rev: master
  link: src/driving_swarm_pheromones

- name: usb_cam
  repo: https://github.com/ros-drivers/usb_cam.git
  rev: develop
  link: src/usb_cam

- name: whycon
  repo: git@github.com:ovgu-FINken/WhyCon_Ros.git
  rev: multi
  link: src/whycon
